version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: users-app
    restart: always
    working_dir: /var/www/

    volumes:
      - ../src:/var/www/
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./www.conf:/usr/local/etc/php-fpm.d/www.conf

  nginx:
    image: nginx:1.19-alpine
    container_name: users-nginx
    restart: always
    ports:
      - "6969:80"
    links:
      - mysql:mysql
      - app
    volumes:
      - ../src:/var/www
      - ./nginx:/etc/nginx/conf.d
  mysql:
    image: mysql:5.7
    ports:
      - "3369:3306"
    container_name: users-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: users
      MYSQL_USER: og
      MYSQL_PASSWORD: password
    restart: always
